#!/bin/bash
# Tests for maintainers/check-template-clean.sh — CI guard against project-shell
# artifacts landing in the template repo.
# Pure bash + git, no test runner required (this template repo ships no JS suite).
# Run: bash .claude/tests/check-template-clean.test.sh
set -u

SCRIPT="$(cd "$(dirname "$0")/../.." && pwd)/maintainers/check-template-clean.sh"

# The guard is maintainer tooling — a consumer repo that deleted maintainers/
# still ships this suite, so skip cleanly instead of failing.
if [ ! -f "$SCRIPT" ]; then
  echo "  - maintainers/check-template-clean.sh not present — skipping (consumer repo)"
  echo ""
  echo "Results: 0 passed, 0 failed"
  exit 0
fi

PASS=0; FAIL=0
ok() { echo "  ✓ $1"; PASS=$((PASS + 1)); }
no() { echo "  ✗ $1"; FAIL=$((FAIL + 1)); }

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# A minimal clean template repo: template files only, placeholder docs, the
# guv's own README (mid-line marker mention in prose — must NOT trip the
# rendered-README check), and README.template.md with line-anchored markers
# (legitimate — must NOT trip it either).
make_template() {
  local r="$WORK/tpl"
  rm -rf "$r"
  mkdir -p "$r/docs/sessions" "$r/.claude"
  echo "template" > "$r/CLAUDE.template.md"
  printf '# [PROJECT NAME] — Development Plan & Requirements\n' > "$r/docs/REQUIREMENTS.md"
  printf '# [PROJECT NAME] — Technical Architecture\n' > "$r/docs/ARCHITECTURE.md"
  printf '# Phase Status Tracker\n## Phase 1 — [Phase Name]\n' > "$r/docs/PHASE_STATUS.md"
  touch "$r/docs/sessions/.gitkeep"
  printf '# guv README\nKeep the `<!-- STATUS:START/END -->` markers when rendering.\n' > "$r/README.md"
  printf '# [PROJECT NAME]\n<!-- STATUS:START (generated by /handoff) -->\n_Status: not yet scaffolded._\n<!-- STATUS:END -->\n' > "$r/README.template.md"
  git -C "$r" init -q
  git -C "$r" config user.email t@t
  git -C "$r" config user.name t
  git -C "$r" add -A
  git -C "$r" commit -qm init
  echo "$r"
}
commit() { git -C "$1" add -A && git -C "$1" commit -qm "$2"; }
run() { ( cd "$1" && bash "$SCRIPT" ) 2>&1; }

# T1 — clean template (incl. anchored markers in README.template.md and a
# mid-line marker mention in the repo's own README) → exit 0.
R=$(make_template)
OUT=$(run "$R"); RC=$?
[ "$RC" -eq 0 ] && ok "clean template: exit 0" || no "clean template should exit 0 (rc=$RC): $OUT"

# T2 — tracked rendered CLAUDE.md → fail, named.
R=$(make_template)
echo "rendered" > "$R/CLAUDE.md"
commit "$R" leak
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "tracked CLAUDE.md: exit non-zero" || no "tracked CLAUDE.md should fail"
echo "$OUT" | grep -q "CLAUDE.md" && ok "tracked CLAUDE.md: named in output" || no "output should name CLAUDE.md (got: $OUT)"

# T3 — UNtracked CLAUDE.md (scratch in the working tree) → still clean.
R=$(make_template)
echo "scratch" > "$R/CLAUDE.md"
OUT=$(run "$R"); RC=$?
[ "$RC" -eq 0 ] && ok "untracked CLAUDE.md: ignored (exit 0)" || no "untracked files must not fail the guard (got: $OUT)"

# T4 — tracked feedback log → fail.
R=$(make_template)
mkdir -p "$R/.claude/feedback"
echo '{"id":"x"}' > "$R/.claude/feedback/feedback.ndjson"
commit "$R" leak
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "tracked .claude/feedback/: exit non-zero" || no "tracked feedback log should fail"
echo "$OUT" | grep -q "feedback" && ok "feedback leak: named in output" || no "output should name the feedback log (got: $OUT)"

# T5 — tracked session handoff → fail, named (.gitkeep alone is fine per T1).
R=$(make_template)
echo "# handoff" > "$R/docs/sessions/session-2026-06-10-001.md"
commit "$R" leak
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "tracked session handoff: exit non-zero" || no "tracked session handoff should fail"
echo "$OUT" | grep -q "session-2026-06-10-001.md" && ok "session leak: file named" || no "output should name the session file (got: $OUT)"

# T6 — rendered project README (line-anchored STATUS marker) → fail.
R=$(make_template)
printf '# My Project\n<!-- STATUS:START (generated by /handoff) -->\nPhase 1\n<!-- STATUS:END -->\n' > "$R/README.md"
commit "$R" leak
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "rendered README.md: exit non-zero" || no "rendered README should fail"
echo "$OUT" | grep -q "README.md" && ok "rendered README: named in output" || no "output should name README.md (got: $OUT)"

# T7 — filled-in (non-placeholder) docs → fail, named. All three files checked.
for doc in docs/REQUIREMENTS.md docs/ARCHITECTURE.md docs/PHASE_STATUS.md; do
  R=$(make_template)
  printf '# Acme\nreal content, placeholders gone\n' > "$R/$doc"
  commit "$R" leak
  OUT=$(run "$R"); RC=$?
  [ "$RC" -ne 0 ] && echo "$OUT" | grep -q "$doc" \
    && ok "filled $doc: fails and names the file" \
    || no "filled $doc should fail and be named (rc=$RC, got: $OUT)"
done

# T7b — unstaged working-tree edits do NOT count: render README.md in the
# working tree only (tracked content still clean) → exit 0; stage it → fail.
R=$(make_template)
printf '# My Project\n<!-- STATUS:START (generated) -->\nPhase 1\n<!-- STATUS:END -->\n' > "$R/README.md"
OUT=$(run "$R"); RC=$?
[ "$RC" -eq 0 ] && ok "unstaged README render: ignored (index is clean)" || no "unstaged working-tree edits must not fail (got: $OUT)"
git -C "$R" add README.md
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "staged README render: caught before commit" || no "a staged violation should fail (got: $OUT)"

# T7c — other shell artifacts: agent-memory content, settings.local.json, UAT
# docs, archived initiatives.
R=$(make_template)
mkdir -p "$R/.claude/agent-memory/reviewer" "$R/docs/uat" "$R/docs/initiatives/001-x"
echo "# frozen tracker" > "$R/docs/initiatives/001-x/PHASE_STATUS.md"
echo "learned" > "$R/.claude/agent-memory/reviewer/MEMORY.md"
echo '{}' > "$R/.claude/settings.local.json"
# force-add: the leak scenario is precisely a force-add past gitignore (and a
# global ~/.config/git/ignore may otherwise swallow this file from the fixture)
git -C "$R" add -f .claude/settings.local.json
echo "# uat" > "$R/docs/uat/phase-1-uat.md"
commit "$R" leak
OUT=$(run "$R")
echo "$OUT" | grep -q "agent-memory" && ok "tracked agent-memory: flagged" || no "tracked agent-memory should be flagged (got: $OUT)"
echo "$OUT" | grep -q "settings.local.json" && ok "tracked settings.local.json: flagged" || no "tracked settings.local.json should be flagged (got: $OUT)"
echo "$OUT" | grep -q "docs/uat" && ok "tracked docs/uat: flagged" || no "tracked docs/uat should be flagged (got: $OUT)"
echo "$OUT" | grep -q "docs/initiatives" && ok "tracked docs/initiatives: flagged" || no "tracked docs/initiatives should be flagged (got: $OUT)"

# T7d — .gitkeep exemption is exact-path: dir's own .gitkeep is fine,
# a session file merely *ending* in .gitkeep is not.
R=$(make_template)
mkdir -p "$R/.claude/feedback"
touch "$R/.claude/feedback/.gitkeep"
echo "x" > "$R/docs/sessions/notes.gitkeep"
commit "$R" leak
OUT=$(run "$R"); RC=$?
[ "$RC" -ne 0 ] && ok "gitkeep mix: exits non-zero (notes.gitkeep is a violation)" || no "notes.gitkeep should make the guard fail (rc=$RC)"
echo "$OUT" | grep -q "feedback" && no "feedback/.gitkeep placeholder should be exempt (got: $OUT)" || ok "feedback/.gitkeep placeholder: exempt"
echo "$OUT" | grep -q "notes.gitkeep" && ok "sessions/notes.gitkeep: NOT exempt (exact-path rule)" || no "only the directory's own .gitkeep is exempt (got: $OUT)"

# T10 — consumer skip path: a repo that deleted maintainers/ runs this very test
# file from its suite loop and gets a clean skip (exit 0), not a failure.
SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
D="$WORK/consumer/.claude/tests"
mkdir -p "$D"
cp "$SELF" "$D/"
OUT=$(bash "$D/$(basename "$0")"); RC=$?
[ "$RC" -eq 0 ] && echo "$OUT" | grep -q "skipping" \
  && ok "consumer repo (no maintainers/): suite skips cleanly" \
  || no "suite should skip with exit 0 when maintainers/ is absent (rc=$RC, got: $OUT)"

# T8 — multiple violations are ALL reported, not just the first.
R=$(make_template)
echo "rendered" > "$R/CLAUDE.md"
echo "# handoff" > "$R/docs/sessions/session-x.md"
commit "$R" leak
OUT=$(run "$R")
N=$(echo "$OUT" | grep -c '✗')
[ "$N" -ge 2 ] && ok "multiple violations: all reported ($N)" || no "should report every violation, got $N: $OUT"

# T9 — works from a subdirectory (CI may not always run at repo root).
R=$(make_template)
echo "rendered" > "$R/CLAUDE.md"
commit "$R" leak
OUT=$( ( cd "$R/docs" && bash "$SCRIPT" ) 2>&1 ); RC=$?
[ "$RC" -ne 0 ] && ok "run from subdir: violation still caught" || no "should work from a subdirectory (got: $OUT)"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
