#!/bin/bash
# Tests for the calibrated-vet PROSE invariants ([18.2], Phase 18) — the judgment
# half of the deliverable, which lives in the generation-point skill prose: handoff
# Step 8 + uat-plan.md (the UAT generation surface) and manual/SKILL.md (the card
# surface). The qa-stamp.sh helper is the MECHANICAL half (pinned by qa-stamp.test.sh);
# this suite pins the JUDGMENT contract the prose must carry at each generation point,
# so the two surfaces cannot silently lose the calibrated vet (guv-verification Rule 8
# — the doc-drift guard, modeled on fanout-offer-prose.test.sh).
#
# The contract, per the [18.2] acceptance clauses + Spike S3
# (docs/spikes/18-1-generated-artifact-qa.md):
#   - a generated UAT routes to the EVALUATOR by name, INDEPENDENT of the reviewer
#     that generated it; a manual card routes to the REVIEWER by name — calibrated
#     agents, ad-hoc verifier prohibited (Rule 14);
#   - the verdict is RECORDED (the written record) AND STAMPED (qa-stamp.sh);
#   - the vet is DECLARED-NOT-GATED: a failing vet does not block the handoff, the
#     session exits 0 (the Rule-15 exit-0 rung);
#   - a review that cannot run degrades to UNVETTED — never a silent pass.
#
# This suite asserts SOURCE SKILL.md prose, so it is MAINTAINER-ONLY by build-plugin.sh's
# partition (it references skills/<x>/SKILL.md) — it runs in the core battery and never
# ships, exactly like fanout-offer-prose.test.sh. ship-suite.test.sh asserts that.
# Pure bash + grep. Run: bash .claude/tests/qa-vet-prose.test.sh
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HANDOFF="$ROOT/skills/handoff/SKILL.md"
UATPLAN="$ROOT/skills/handoff/uat-plan.md"
MANUAL="$ROOT/skills/manual/SKILL.md"

PASS=0; FAIL=0
ok() { echo "  ✓ $1"; PASS=$((PASS + 1)); }
no() { echo "  ✗ $1"; FAIL=$((FAIL + 1)); }

# Precondition: all three prose surfaces exist (a missing file is a loud failure, not a
# silent skip — Rule 15).
for f in "$HANDOFF" "$UATPLAN" "$MANUAL"; do
  [ -f "$f" ] || no "expected prose surface missing: $f"
done

# Flatten a file to one whitespace-normalized line before matching, so a multi-word
# contract phrase matches regardless of where markdown soft-wraps it (a per-line grep
# would falsely redden on a phrase split across a wrap). Prose reflows; the contract is
# the words.
has() { # $1=file  $2=pattern  $3=label
  local flat
  flat=$(tr '\n' ' ' < "$1" | tr -s ' ')
  if printf '%s' "$flat" | grep -qE "$2"; then
    ok "$3"
  else
    no "MISSING in $(basename "$(dirname "$1")")/$(basename "$1"): $3 (pattern: $2)"
  fi
}

# ════════════════ UAT generation surface — uat-plan.md (authoritative home) ════════════════
echo "— UAT vet (uat-plan.md) —"

# 1 — the vet routes to the EVALUATOR by name, INDEPENDENT of the generating reviewer.
has "$UATPLAN" '[Ee]valuator' "uat-plan: routes the UAT vet to the evaluator"
has "$UATPLAN" 'by name' "uat-plan: invokes the evaluator BY NAME (Rule 14)"
has "$UATPLAN" 'independent of the' "uat-plan: the vet is INDEPENDENT of the generator"
has "$UATPLAN" '[Rr]eviewer generated|generated (these|the) scenarios|generated by the .?reviewer' \
  "uat-plan: names the reviewer as the generator (so the evaluator vet is the independent second eye)"

# 2 — Rule 14, ad-hoc verifier prohibited.
has "$UATPLAN" 'Rule 14' "uat-plan: cites Rule 14 (calibrated, not ad-hoc)"

# 3 — declared-not-gated: the failing vet does NOT block the handoff; the session exits 0.
has "$UATPLAN" 'declared-not-gated|declared not gated' "uat-plan: the vet is declared-not-gated"
has "$UATPLAN" 'does .?.?not.?.? block the handoff|not block the handoff' \
  "uat-plan: a NEEDS WORK verdict does NOT block the handoff"
has "$UATPLAN" 'exit 0|exits 0|exit-0' "uat-plan: the session still exits 0 (the Rule-15 exit-0 rung)"

# 4 — the verdict is RECORDED in the written record (the handoff artifact).
has "$UATPLAN" '[Rr]ecord' "uat-plan: the verdict is recorded in the written record"
has "$UATPLAN" 'Issues & Technical Debt|handoff artifact' \
  "uat-plan: names the record home (handoff artifact / Issues & Technical Debt)"

# 5 — the verdict is STAMPED via the canonical helper.
has "$UATPLAN" 'qa-stamp\.sh' "uat-plan: stamps the verdict via qa-stamp.sh (the canonical helper)"

# 6 — the review-unavailable path degrades to UNVETTED, never a silent pass.
has "$UATPLAN" 'UNVETTED' "uat-plan: a review that cannot run degrades to UNVETTED"
has "$UATPLAN" 'never a silent pass|not a silent pass|never .{0,20}silent|rather than .{0,30}passed' \
  "uat-plan: UNVETTED is loud — never a silent pass"

# ════════════════ UAT generation surface — handoff Step 8 (the bridge) ════════════════
echo "— UAT vet bridge (handoff Step 8) —"

# The contract must be VISIBLE at the generation point too — Step 8 names the evaluator
# vet, its independence from the generator, and that it is declared-not-gated, then
# points to uat-plan.md for the mechanics.
has "$HANDOFF" 'vet .{0,30}via the.{0,6}evaluator|vet it via the.{0,6}evaluator|then .{0,6}vet.{0,40}evaluator' \
  "handoff Step 8: names the evaluator vet at the UAT generation point"
has "$HANDOFF" 'independent of the.{0,8}reviewer|independent of its generator' \
  "handoff Step 8: the vet is independent of the generating reviewer"
has "$HANDOFF" 'declared-not-gated|declared not gated' \
  "handoff Step 8: states the vet is declared-not-gated"

# ════════════════ Manual card surface — manual/SKILL.md ════════════════
echo "— Manual card vet (manual/SKILL.md) —"

# 1 — the card routes to the REVIEWER by name.
has "$MANUAL" 'vet .{0,40}reviewer|vet the .{0,20}card.{0,20}reviewer|reviewer.{0,30}vet' \
  "manual: routes the card vet to the reviewer"
has "$MANUAL" 'by name' "manual: invokes the reviewer BY NAME (Rule 14)"
has "$MANUAL" 'Rule 14' "manual: cites Rule 14 (calibrated, not ad-hoc)"

# 2 — declared-not-gated: the vet does not block creating the artifact / the session exits 0.
has "$MANUAL" 'declared-not-gated|declared not gated' "manual: the vet is declared-not-gated"
has "$MANUAL" 'exit 0|exits 0|exit-0|does not block|not block' \
  "manual: a NEEDS WORK verdict does not block (exit-0 rung)"

# 3 — the verdict is RECORDED and STAMPED.
has "$MANUAL" '[Rr]ecord' "manual: the verdict is recorded in the written record"
has "$MANUAL" 'qa-stamp\.sh' "manual: stamps the verdict via qa-stamp.sh"

# 4 — UNVETTED degrade, never a silent pass.
has "$MANUAL" 'UNVETTED' "manual: a review that cannot run degrades to UNVETTED"
has "$MANUAL" 'never a silent pass|not a silent pass|never .{0,20}silent' \
  "manual: UNVETTED is loud — never a silent pass"

# ════════════════ Routing parity — the independence guarantee (the heart) ════════════════
echo "— routing parity —"
# The whole value is that each artifact is vetted by an agent INDEPENDENT of the one
# that generated it: the reviewer generates the UAT → the evaluator vets it; the agent
# drafts the card → the reviewer vets it. Pin the cross-routing so a future edit that
# collapses both onto one reviewer (losing independence) reddens here.
uflat=$(tr '\n' ' ' < "$UATPLAN" | tr -s ' ')
mflat=$(tr '\n' ' ' < "$MANUAL" | tr -s ' ')
printf '%s' "$uflat" | grep -qE 'evaluator' && printf '%s' "$mflat" | grep -qE 'reviewer' \
  && ok "parity: UAT→evaluator, card→reviewer (each vetted independent of its generator)" \
  || no "the UAT must route to the evaluator and the card to the reviewer"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
